// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQ9gE3uAaYQbi1BgEYI374xFfFzP6vqE',
    appId: '1:1041151177820:web:5cd0d9aff3424a42e6e299',
    messagingSenderId: '1041151177820',
    projectId: 'turkey-5b3f5',
    authDomain: 'turkey-5b3f5.firebaseapp.com',
    storageBucket: 'turkey-5b3f5.firebasestorage.app',
    measurementId: 'G-T2644H644K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdHMr_TENOweY7lWd9Ek0HYBl_mKqeH9Y',
    appId: '1:1041151177820:android:e16966499504be5ae6e299',
    messagingSenderId: '1041151177820',
    projectId: 'turkey-5b3f5',
    storageBucket: 'turkey-5b3f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAulz94221cNCf9Ci1WERFCoPrroJdnsg8',
    appId: '1:1041151177820:ios:1504fd6f0ad8ccb2e6e299',
    messagingSenderId: '1041151177820',
    projectId: 'turkey-5b3f5',
    storageBucket: 'turkey-5b3f5.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAulz94221cNCf9Ci1WERFCoPrroJdnsg8',
    appId: '1:1041151177820:ios:1504fd6f0ad8ccb2e6e299',
    messagingSenderId: '1041151177820',
    projectId: 'turkey-5b3f5',
    storageBucket: 'turkey-5b3f5.firebasestorage.app',
    iosBundleId: 'com.example.untitled3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbQ9gE3uAaYQbi1BgEYI374xFfFzP6vqE',
    appId: '1:1041151177820:web:140aaa92abaa86e8e6e299',
    messagingSenderId: '1041151177820',
    projectId: 'turkey-5b3f5',
    authDomain: 'turkey-5b3f5.firebaseapp.com',
    storageBucket: 'turkey-5b3f5.firebasestorage.app',
    measurementId: 'G-Q3KR0MVNEJ',
  );
}
